services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ticket
      MYSQL_DATABASE: ticketeer
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080